Adding find_spec to ModuleImporterFromVariables
amoffat/sh pull request #536
Opened 2020-08-27 20:42 UTC by sbacchio

This PR adds the method `find_spec` to `ModuleImporterFromVariables`.

The method `find_module` (implemented in `ModuleImporterFromVariables`) has been deprecated since Python 3.4 in favor of `find_spec`: https://docs.python.org/3/library/sys.html#sys.meta_path

The absence of `find_spec` made me incur in an issue with pytest: https://github.com/pytest-dev/pytest/issues/7689.
This PR would resolve that issue.

2020-08-28 05:29 UTC, ecederstrand requested changes
Thanks for the contribution!

2020-08-28 05:29 UTC, ecederstrand commented on sh.py
> +__version__ = "1.13.2"
Please don't bump the package version here. We'll do that in a separate commit when we are ready to release a new version.

2020-08-28 05:29 UTC, ecederstrand commented on sh.py
> +    def find_spec(self, fullname, path=None, target=None):
Please change the string comment to proper docsting format (triple-quote).

We normally don't do lazy imports, but I don't see a good way around it because we also don't do top-level imports for things that don't have an equivalent in older Python versions. Let's leave it here.

We could consider putting the `find_spec()` definition itself under `if IS_PY3 and MINOR_VER >= 4: def find_spec(...` but as long as we have the comment, I don't really see the value.

2020-08-28 05:39 UTC, sbacchio commented on sh.py
> +    def find_spec(self, fullname, path=None, target=None):
Done

2020-08-28 05:39 UTC, sbacchio commented on sh.py
> +__version__ = "1.13.2"
Ok, sorry about that!

2020-08-28 05:58 UTC, merged

2020-08-29 02:20 UTC, amoffat commented
:+1: Good work all. Release 1.14.0 is out with these changes